apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{name}}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{name}}
    spec:
      containers:
      - name: {{name}}
        image: asia.gcr.io/{{project-id}}/{{name}}:${CIRCLE_SHA1}
        ports:
        - containerPort: 8080
        env:
          - name: {{screaming-snake}}_MY_WEBAPP_PORT
            value: 8080
          - name: {{screaming-snake}}_EXAMPLE_PORT
            value: 8000
